export enum FinnhubApiConstant {
    AUTH_TOKEN_HEADER_KEY = "X-Finnhub-Token",
    METADATA_SEARCH_QUERY_PARAM = "q",
    SYMBOL_QUERY_PARAM = "symbol",
    STOCK_SYMBOL_METADATA_SEARCH_EXCHANGE_CODE = "exchange",
    STOCK_SYMBOL_METADATA_SEARCH_EXCHANGE_CODE_DEFAULT = "US",
    STOCK_SYMBOL_PRICE_CHECK_PATH = "/quote",
    STOCK_SYMBOL_METADATA_PATH = "/search",
}
